FROM maven:3.8.3-openjdk-17 AS build

WORKDIR /app

COPY ./PetsyBackend/pom.xml .
COPY ./PetsyBackend/src ./src

RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=build /app/target/*.jar /app/moja-aplikacja.jar

ENTRYPOINT ["java", "-jar", "/app/moja-aplikacja.jar"]