version: '3.9'

services:
  sql:
    image: mysql
    container_name: PetsyDataBase
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: PetsyDataBase
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_USER: user1
      MYSQL_PASSWORD: haslo1
    networks:
      - mynetwork
  myapp:
    container_name: PetsyBackendServer

    build:
      dockerfile: ./PetsyBackend/Dockerfile

    ports:
      - "8080:8080"
    restart: on-failure

    environment:
      DATABASE_HOST: sql
      DATABASE_PORT: 3306
      DATABASE_NAME: PetsyDataBase
      DATABASE_USER: user1
      DATABASE_PASSWORD: haslo1

    depends_on:
      - sql
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
